import os
import yaml

# List of all workflows
WORKFLOWS = [
    "ai.image_generate",
    "browser.open_url",
    "browser.scrape",
    "calendar.create_event",
    "calendar.list_events",
    "communication.send_email",
    # "communication.send_message" (Already created)
    "docker.container_control",
    "filesystem.read",
    "filesystem.write",
    "iot.device_control",
    "knowledge.capture",
    "knowledge.search",
    "productivity.create_task",
    "sdk.echo",
    "system.notification"
]

# Map to generate Abstract Intent and basic Schema
CAPABILITY_METADATA = {
    "ai.image_generate": {"intent": "GenerateImage", "props": {"prompt": "string"}},
    "browser.open_url": {"intent": "OpenURL", "props": {"url": "string"}},
    "browser.scrape": {"intent": "ScrapeWebsite", "props": {"url": "string"}},
    "calendar.create_event": {"intent": "CreateCalendarEvent", "props": {"title": "string", "start_time": "string", "end_time": "string"}},
    "calendar.list_events": {"intent": "ListCalendarEvents", "props": {"date": "string"}},
    "communication.send_email": {"intent": "SendEmail", "props": {"to": "string", "subject": "string", "body": "string"}},
    "docker.container_control": {"intent": "ControlContainer", "props": {"container_id": "string", "action": "string"}},
    "filesystem.read": {"intent": "ReadFile", "props": {"path": "string"}},
    "filesystem.write": {"intent": "WriteFile", "props": {"path": "string", "content": "string"}},
    "iot.device_control": {"intent": "ControlIoTDevice", "props": {"device_id": "string", "action": "string", "value": "string"}},
    "knowledge.capture": {"intent": "CaptureKnowledge", "props": {"content": "string", "tags": "string"}},
    "knowledge.search": {"intent": "SearchKnowledge", "props": {"query": "string"}},
    "productivity.create_task": {"intent": "CreateTask", "props": {"title": "string", "description": "string"}},
    "sdk.echo": {"intent": "EchoPing", "props": {"message": "string"}},
    "system.notification": {"intent": "SendNotification", "props": {"message": "string", "level": "string"}}
}

def main():
    base_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "apps", "api", "plugins", "n8n_core", "capabilities"))
    os.makedirs(base_dir, exist_ok=True)
    
    for wf in WORKFLOWS:
        meta = CAPABILITY_METADATA.get(wf, {"intent": "Unknown", "props": {"payload": "object"}})
        
        # Build YAML struct
        data = {
            "name": f"n8n.{wf}",
            "abstract_intent": meta["intent"],
            "description": f"Autogenerated capability for {wf}",
            "driver": "rest_n8n",
            "endpoint": f"/webhook/{wf.replace('.', '/')}",
            "method": "POST",
            "schema": {
                "type": "object",
                "properties": meta["props"]
            }
        }
        
        file_path = os.path.join(base_dir, f"{wf.split('.')[-1]}.yaml")
        with open(file_path, "w", encoding="utf-8") as f:
            yaml.dump(data, f, sort_keys=False, default_flow_style=False)
            
        print(f"Generated: {file_path}")

if __name__ == "__main__":
    main()
